Repository lingfo/lingfo, pull requests merged in 2023-03, with the labels that each got.

#9 Add multiple file support
  src/sushipy/execute.py
  src/sushipy/index.py
  src/sushipy/main.py
  src/sushipy/stores.py
Labels: enhancement, priority: important

#16 Fix positional arguments when calling function with arguments
  setup.cfg
  src/sushipy/execute.py
  src/sushipy/index.py
  tests/test_execute.py
Labels: bug

#26 Add verbose mode
  src/sushipy/config/extends.py
  src/sushipy/execute.py
  src/sushipy/index.py
  src/sushipy/main.py
  src/sushipy/stores.py
  src/sushipy/utils/verbose_print.py
Labels: work in progress

#20 add one time compile
  src/sushipy/cache/cache_template.py
  src/sushipy/cache/main.py
  src/sushipy/config/extends.py
  src/sushipy/execute.py
  src/sushipy/index.py
  src/sushipy/one_compile.py
  src/sushipy/stores.py
Labels: priority: nice to have, work in progress
